---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis-cart
  namespace: microservices-demo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.0
spec:
  releaseName: redis-cart
  helmVersion: v3
  chart:
    git: git@gitlab.com:1Psy/microservices-demo.git
    ref: master
    path: deploy/charts/redis-cart
  values:
    image:
      repository: redis
      tag: alpine
