apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics
spec:
  selector:
    matchLabels:
      app: nginx-svc
  endpoints:
    - port: metrics
      path: /metrics
