apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-reverse
  labels:
    app: paymentservice-reverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice-reverse
  template:
    metadata:
      labels:
        app: paymentservice-reverse
    spec:
      containers:
      - name: paymentservice
        image: travk/hipster-paymentservice:0.2
  strategy:
    type: Recreate
