apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend-healthy
  name: frontend-healthy
spec:
  containers:
  - image: travk/hipster-frontend:0.1
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "null"
    - name: CURRENCY_SERVICE_ADDR
      value: "null"
    - name: CART_SERVICE_ADDR
      value: "null"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "null"
    - name: SHIPPING_SERVICE_ADDR
      value: "null"
    - name: CHECKOUT_SERVICE_ADDR
      value: "null"
    - name: AD_SERVICE_ADDR
      value: "null"
  restartPolicy: Never